management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  jackson:
    default-property-inclusion: NON_NULL
    date-format: "yyyy-MM-dd'T'HH:mm:ss:SSSZ"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false