# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### POST A DOCUMENT

POST {{host-url}}//api/v1/documents/
Content-Type: application/json

{
  "title": "created",
  "body": "string"
}

### FIND ALL DOCUMENTS

GET {{host-url}}//api/v1/documents/

### FIND A DOCUMENT BY ITS ID

GET {{host-url}}//api/v1/documents/5dee400b371a5716505b3e85

### UPDATE A DOCUMENT

POST {{host-url}}//api/v1/documents/5dee400b371a5716505b3e85
Content-Type: application/json

{
  "title": "edited",
  "body": "string"
}

### GET LOCK FROM A DOCUMENT

GET {{host-url}}//api/v1/documents/5dee400b371a5716505b3e85/lock

### UPDATE LOCK FROM A DOCUMENT

PUT {{host-url}}//api/v1/documents/5dee400b371a5716505b3e85/lock

### DELETE LOCK FROM A DOCUMENT

DELETE {{host-url}}//api/v1/documents/5dee400b371a5716505b3e85/lock

###
